--------------------------------------------------------
--  파일이 생성됨 - 목요일-5월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_ADMIN
--------------------------------------------------------

  CREATE TABLE "MES"."TB_ADMIN" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"ADMIN_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"ADMIN_PASSWORD" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "TB_ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "MES"."TB_ADMIN"."ID" IS '관리자 고유ID'
   COMMENT ON COLUMN "MES"."TB_ADMIN"."ADMIN_ID" IS '관리자ID'
   COMMENT ON COLUMN "MES"."TB_ADMIN"."ADMIN_PASSWORD" IS '관리자 비밀번호'
--------------------------------------------------------
--  DDL for Table TB_ORDER
--------------------------------------------------------

  CREATE TABLE "MES"."TB_ORDER" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"ADMIN_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(50), 
	"PRODUCT_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"ROBOT_ID" VARCHAR2(50), 
	"FROM_STATION_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"TO_STATION_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PRODUCT_COUNT" NUMBER NOT NULL ENABLE, 
	"FROM_STATION_SIGNAL" NUMBER, 
	"TO_STATION_SIGNAL" NUMBER, 
	"ORDER_AT" DATE NOT NULL ENABLE, 
	"COMPLETE_AT" DATE, 
	 CONSTRAINT "TB_ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table TB_PRODUCT
--------------------------------------------------------

  CREATE TABLE "MES"."TB_PRODUCT" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PRODUCT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"GOAL_COUNT" NUMBER NOT NULL ENABLE, 
	"COMPLETE_AT" DATE, 
	 CONSTRAINT "TB_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table TB_ROBOT
--------------------------------------------------------

  CREATE TABLE "MES"."TB_ROBOT" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"ROBOT_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "TB_ROBOT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table TB_ROBOTCONTROLL
--------------------------------------------------------

  CREATE TABLE "MES"."TB_ROBOTCONTROLL" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"ROBOT_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	"BETTERY_LEVEL" NUMBER NOT NULL ENABLE, 
	"ISEMERGENCY" NUMBER NOT NULL ENABLE, 
	"SPEED" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "TB_ROBOTCONTROLL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table TB_STATION
--------------------------------------------------------

  CREATE TABLE "MES"."TB_STATION" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"STATION_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"STATION_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "TB_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table TB_USER
--------------------------------------------------------

  CREATE TABLE "MES"."TB_USER" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "TB_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into MES.TB_ADMIN
SET DEFINE OFF;
REM INSERTING into MES.TB_ORDER
SET DEFINE OFF;
Insert into MES.TB_ORDER (ID,ADMIN_ID,USER_ID,PRODUCT_ID,ROBOT_ID,FROM_STATION_ID,TO_STATION_ID,PRODUCT_COUNT,FROM_STATION_SIGNAL,TO_STATION_SIGNAL,ORDER_AT,COMPLETE_AT) values ('05202511440123','Admin',null,'G_LD',null,'G1','G2',10,null,null,to_date('25/05/01','RR/MM/DD'),null);
REM INSERTING into MES.TB_PRODUCT
SET DEFINE OFF;
Insert into MES.TB_PRODUCT (ID,PRODUCT_NAME,PRODUCT_TYPE,GOAL_COUNT,COMPLETE_AT) values ('04202515173020','G_LD','그렌저차체',10,null);
REM INSERTING into MES.TB_ROBOT
SET DEFINE OFF;
Insert into MES.TB_ROBOT (ID,ROBOT_NAME) values ('05202509340148','Robot1');
REM INSERTING into MES.TB_ROBOTCONTROLL
SET DEFINE OFF;
Insert into MES.TB_ROBOTCONTROLL (ID,ROBOT_NAME,STATUS,BETTERY_LEVEL,ISEMERGENCY,SPEED) values ('05202509340148','Robot1','1',100,1,100);
REM INSERTING into MES.TB_STATION
SET DEFINE OFF;
Insert into MES.TB_STATION (ID,STATION_NAME,STATION_TYPE) values ('20250430095524','P2','포터');
Insert into MES.TB_STATION (ID,STATION_NAME,STATION_TYPE) values ('20250430110812','G2','그렌저');
Insert into MES.TB_STATION (ID,STATION_NAME,STATION_TYPE) values ('20250430110841','G1','그렌저');
Insert into MES.TB_STATION (ID,STATION_NAME,STATION_TYPE) values ('20250430095505','P1','포터');
REM INSERTING into MES.TB_USER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TB_PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MES"."TB_PRODUCT_PK" ON "MES"."TB_PRODUCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index TB_STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MES"."TB_STATION_PK" ON "MES"."TB_STATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index TB_ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MES"."TB_ADMIN_PK" ON "MES"."TB_ADMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index TB_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MES"."TB_USER_PK" ON "MES"."TB_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index TB_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MES"."TB_ORDER_PK" ON "MES"."TB_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index TB_ROBOT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MES"."TB_ROBOT_PK" ON "MES"."TB_ROBOT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index TB_ROBOTCONTROLL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MES"."TB_ROBOTCONTROLL_PK" ON "MES"."TB_ROBOTCONTROLL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Trigger TRG_DELETE_ROBOT_CONTROL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MES"."TRG_DELETE_ROBOT_CONTROL" 
AFTER DELETE ON tb_robot
FOR EACH ROW
BEGIN
    DELETE FROM tb_robotcontroll
    WHERE ID = :OLD.ID;
END;

ALTER TRIGGER "MES"."TRG_DELETE_ROBOT_CONTROL" ENABLE
--------------------------------------------------------
--  DDL for Trigger TRG_INSERT_ROBOT_CONTROL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MES"."TRG_INSERT_ROBOT_CONTROL" 
AFTER INSERT ON tb_robot
FOR EACH ROW
BEGIN
    INSERT INTO tb_robotcontroll (
        ID,
        robot_name,
        STATUS,
        BETTERY_LEVEL,
        ISEMERGENCY,
        SPEED
    )
    VALUES (
        :NEW.ID,
        :NEW.robot_name,
        1,        -- robot_status
        100,      -- battery_level
        1,        -- emergency_stop
        100       -- work_speed
    );
END;

ALTER TRIGGER "MES"."TRG_INSERT_ROBOT_CONTROL" ENABLE
--------------------------------------------------------
--  DDL for Trigger TRG_ROBOT_STATUS_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MES"."TRG_ROBOT_STATUS_UPDATE" 
AFTER UPDATE OF status ON TB_ROBOTCONTROLL
FOR EACH ROW
 WHEN (OLD.status = 3 AND NEW.status = 1) BEGIN
    UPDATE TB_ROBOTCONTROLL
    SET BETTERY_LEVEL = BETTERY_LEVEL - 20
    WHERE ID = :NEW.ID;
END;

ALTER TRIGGER "MES"."TRG_ROBOT_STATUS_UPDATE" ENABLE
--------------------------------------------------------
--  DDL for Trigger TRG_UPDATE_ROBOT_NAME
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MES"."TRG_UPDATE_ROBOT_NAME" 
AFTER UPDATE OF robot_name ON tb_robot
FOR EACH ROW
BEGIN
    UPDATE TB_ROBOTCONTROLL
    SET robot_name = :NEW.robot_name
    WHERE ID = :OLD.ID;
END;

ALTER TRIGGER "MES"."TRG_UPDATE_ROBOT_NAME" ENABLE
--------------------------------------------------------
--  Constraints for Table TB_ADMIN
--------------------------------------------------------

  ALTER TABLE "MES"."TB_ADMIN" MODIFY ("ADMIN_PASSWORD" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ADMIN" ADD CONSTRAINT "TB_ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MES"."TB_ADMIN" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table TB_STATION
--------------------------------------------------------

  ALTER TABLE "MES"."TB_STATION" ADD CONSTRAINT "TB_STATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MES"."TB_STATION" MODIFY ("STATION_TYPE" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_STATION" MODIFY ("STATION_NAME" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_STATION" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table TB_ROBOT
--------------------------------------------------------

  ALTER TABLE "MES"."TB_ROBOT" ADD CONSTRAINT "TB_ROBOT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MES"."TB_ROBOT" MODIFY ("ROBOT_NAME" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ROBOT" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table TB_USER
--------------------------------------------------------

  ALTER TABLE "MES"."TB_USER" ADD CONSTRAINT "TB_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MES"."TB_USER" MODIFY ("USER_PASSWORD" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_USER" MODIFY ("USER_ID" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_USER" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table TB_ROBOTCONTROLL
--------------------------------------------------------

  ALTER TABLE "MES"."TB_ROBOTCONTROLL" ADD CONSTRAINT "TB_ROBOTCONTROLL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MES"."TB_ROBOTCONTROLL" MODIFY ("SPEED" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ROBOTCONTROLL" MODIFY ("ISEMERGENCY" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ROBOTCONTROLL" MODIFY ("BETTERY_LEVEL" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ROBOTCONTROLL" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ROBOTCONTROLL" MODIFY ("ROBOT_NAME" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ROBOTCONTROLL" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table TB_ORDER
--------------------------------------------------------

  ALTER TABLE "MES"."TB_ORDER" ADD CONSTRAINT "TB_ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MES"."TB_ORDER" MODIFY ("ORDER_AT" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ORDER" MODIFY ("PRODUCT_COUNT" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ORDER" MODIFY ("TO_STATION_ID" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ORDER" MODIFY ("FROM_STATION_ID" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ORDER" MODIFY ("PRODUCT_ID" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ORDER" MODIFY ("ADMIN_ID" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_ORDER" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table TB_PRODUCT
--------------------------------------------------------

  ALTER TABLE "MES"."TB_PRODUCT" ADD CONSTRAINT "TB_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MES"."TB_PRODUCT" MODIFY ("GOAL_COUNT" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_PRODUCT" MODIFY ("PRODUCT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE)
  ALTER TABLE "MES"."TB_PRODUCT" MODIFY ("ID" NOT NULL ENABLE)
